### PR TITLE
Use assertions for testing

### PR DESCRIPTION
**Pull request by obahareth**
Added `ArabicSupportTester` to loop through all `ExpectedFixedText` objects and assert that their `Expected` value matched their `Fixed` value.

Add `ExpectedFixedText` to all `Arabic3DText` objects on test cases scene, and
setup their `Unfixed` and `Expected` properties accordingly.

Sorry for the other two pull requests, some unwanted files slipped through by mistake.

### CODE REVIEW

**Comment by Konash** [comment]
Thanks!

**Comment by Konash** [comment]
How do you know the "Expected" part? Do you manually insert it?

**Comment by obahareth** [comment]
Yes, check one of the objects in the test case scene and look at the `ExpectedFixedText` script attached to it.

**Comment by obahareth** [comment]
There's probably a cleaner way to do this (maybe entirely through code without using objects in a scene), but I wanted to add to your current way of testing instead of changing everything in one pull request.

**Comment by Konash** [comment]
Cool. I just wanted to confirm that. Manual is fine :)

**Pull request merged**
